server:
  port: 9001
  context-path: /app
spring:
  redis:
    host: 114.116.92.12
    password: shadow
    pool:
      max-wait: 1
      max-idle: 8
      max-active: 8
      min-idle: 0
    port: 6379